### ISSUE TITLE
Power__ for Excel

### ISSUE THREAD

**Issue by AlexC84** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#218]
Power apps for excel (PowerMap, PowerPivot, PowerQuery, PowerView) not available in Office 365 Business, Office 365 Business Premium, Microsoft 365?

I know I now have PowerQuery/Pivot for Excel in my Office 365 Home subscription - I'd be surprised if they weren't included in Business subscriptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@AlexC84 Thanks for your feedback! I've contacted the product team and I'll update the service description (if necessary) based on their feedback.

**Comment by AlexC84** [comment]
Thanks, I've done a bit more reading which seems to confirm that all the power stuff isn't available for the business tiers of Office 365. Surprising given its available on consumer editions

**Comment by SharS** [comment]
@AlexC84 Thanks for your response. The product team reviewed the entries in the service description, and confirmed them with the exception of Power Query, which is not included in Office 2013, although it is available as a separate download. I've updated the article to include that information. One reason that some "Power_" capabilities aren't included in some SKUs is because the SKU doesn't include the desktop version of Excel.
