### ISSUE TITLE
Essentials and Premium data retention policies

### ISSUE THREAD

**Issue by mbigus** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#307]
Retention capabilities by O365 plan across the docs is confusing. 

First Chart above shows no retention policy feature available for either Essentials or Premium. 

Second chart above shows retention as included for Exchange online Plan 1. Sub-note says online archiving package needed for retention holds. Shows as included for Plan 2, but as above first chart says no retention for Essentials or Business. (And I realize retention hold may be different then retention policy on to inactivate a mailbox but I think it needs to be specified)

Essentials includes Exchange Online Plan 1 as per chart at: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options 
and Premium includes Exchange Online Plan 2.

I have found that with a retention policy in place, Essentials email accounts are retained over 30 days when deleted,  and are searchable and exportable without adding the archive package option.

Somehow, it needs to be more clear about retention policies applied to inactive mailboxes versus litigation holds etc and whether Essentials, Premius and other accounts are included. 

Further, https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description - show online archiving is not included with Essential or Premium, and the chart at the bottom shows Retention as included with the archiving package, leading one to believe archiving package is needed for retention on essentials or premium accounts. 

This article: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide - says deleted mailboxes subject to retention policies are retained, but doesn't specify if specific to a subscription type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Office 365 Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@mbigus Thanks for your comments. I have forwarded your request to the product team and will update the content if necessary.

**Comment by aaronlemieux** [comment]
Hi @mbigus 

Thank you for your comments.  After speaking with the product team we are making a variety of changes to these pages, based on your feedback.  All of your items above should be addressed once these changes go live.  However, there are two items I wanted to clarify, as they have already changed or are already accurate.

Regarding the retention policies for inactive mailboxes, this information has been moved to a separate page which you can find [here](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide).

Regarding "I have found that with a retention policy in place, Essentials email accounts are retained over 30 days when deleted, and are searchable and exportable without adding the archive package option." this is the expected behavior as MRM is available for all the service licenses [here](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feature-availability).
