### ISSUE TITLE
Storage lmit shared mailbox E3

### ISSUE THREAD

**Issue by WoutVergauwen** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#390]
According to the mailbox limit table for a shared mailbox with an E3 and an E5 license the limit is 50GB, but note 9 contradicts this: Shared and resource mailboxes don't require a license. However, without a license, these mailboxes are limited to 50 GB. To increase the mailbox size, an E3 or E5 license must be assigned. This will increase the mailbox to 100 GB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by aaronlemieux** [comment]
Hi @WoutVergauwen, thank you for reach out to us.  I've spoked with the team, and it looks like the information in the service description is accurate, and your comment above is also saying the same thing as the existing article, so it's also correct.

"You can have an E3 or E5 tenant. By default, a shared mailbox will not have a license assigned to it, therefore, it will be 50GB in size. That’s because shared mailboxes are never assigned licenses by default.

When you assign the E3/E5 license to a specific shared mailbox, the quota for that specific mailbox will be increased to 100GB.

You could also have a Business Standard tenant. Where a shared mailbox will also, by default, be 50GB in size. If you assigned it a Business Standard license, it would still be 50GB in size (because that’s the size you get with that license). But if you assigned this shared mailbox (which is inside of the Business Standard tenant) – an E3/E5 license, the size of that shared mailbox (and only that one shared mailbox) would be increased to 100GB.

So it is the assignment of the license to the shared mailbox that makes a difference here; shared mailbox could be in any kind of tenant, if it does not have a license assigned, then it will be 50GB."

**Comment by WoutVergauwen** [comment]
Hi @aaronlemieux, thanks for getting back to me.
I understand that this is the case, and when you know how the licensing works you can read it correctly, but when you don't, this is all but clear.
As far as I know, all shared mailboxes are 50GB (if I'm not missing a scenario), as long as there's an EO license.
The title of the table says it refers to the user's subscription, which leads me to believe that it refers to the shared mailbox having that subscription/license assigned, not the tenant.
The table refers to the mailbox size for a user, that can only work when that user has the license assigned (my tenant can be E5, but my user can be an E1), so switching from user to tenant license in the same table is quite confusing.

**Comment by aaronlemieux** [comment]
Hi @WoutVergauwen We've updated this SD per your suggestion and are closing this issue on our end.
