### ISSUE TITLE
Add Inbound/Outbound Connector Limit

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#494]
For Mailflow Scenarios the limits for Inbound/Outbound Connectors would be great.
Outbund: 1800
Inbound: 4450
Outbound for instance is relevant if the customer needs to setup forced TLS with certificate name check. The maximum number of recipients that can be configured with that is 1800 as this is the outbound connector limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits?source=docs)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @myfope I've spoken with the product team, and they request that the service description not be updated, due to the complexity.  

In [How to set up a multifunction device or application to send email using Microsoft 365 or Office 365 | Microsoft Docs](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365)
We simply state that “reasonable limits” are imposed.
