### ISSUE TITLE
Is G1 License type missing?

### ISSUE THREAD

**Issue by geneoliver** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#528]
Surprised to not see G1 licenses.  Also does this apply to GCC for F3?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c55dc71-81ed-864b-ac3f-63ce84688070
* Version Independent ID: 578c9a02-045e-4bf9-6384-d70560c332f0
* Content: [Exchange Online Archiving service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, the product team reviewed the information and:
-- Instead of listing all EXO standalone, E, and F plans for GCC/GCCH/DoD separately, they added a 3rd footnote.
-- Biz Premium and A1, like EXO P1 and O365 E1 plans include a limited (50GB) mailbox and archive but do not included full EOA (this is referenced in footnote 2).
Let me know if you have any other questions.
Thanks!
Ann H.
