### ISSUE TITLE
Use OotW when Outlook OME message won't render

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#550]
[Please clarify that recipients are able to use Outlook on the Web in scenarios when Outlook is unable to display the IRM protected messages due to cross-boundaries restrictions (GCC High / Non-GCC High scenarios]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff8bcc8-4789-dc65-c108-ee0641c7c3b7
* Version Independent ID: 20fff9c3-700c-30f1-0714-535957ef40e9
* Content: [Exchange Online for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, 
I just wanted to get back to you regarding your question.

Here is the comment from the product team:
"Based on what we see in general MT environment, if OWA is unable to render an IRM protected message due to any reason, user can still use OWA for other purposes, like working with other message or modules (Calendar, Contacts, etc.) besides that IRM protected message. And IMO, this does not require any change in service description docs. I see it as just a simple question, if I understand it correctly."

Please let me know if you have any other questions or concerns.
Thanks!
Ann H.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know a clarification note was added to address your comment. "Notes: 1 Outlook on the Web can be used in scenarios when Outlook for Windows is unable to display the IRM protected messages due to cross-boundaries restrictions (GCC High / Non-GCC High scenarios)." Thanks!
