### ISSUE TITLE
Please clarify which GCC subscriptions can be ordered via CSP

### ISSUE THREAD

**Issue by johntchoi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#557]
Microsoft Partner Support let us know that Microsoft 365 Government G5 is not available through CSP.  Can you update the documentation accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86dc9aff-0190-52d9-2ab0-4f236d862739
* Version Independent ID: f6cbf527-2a7d-edd6-49b9-ca70ba43b9d6
* Content: [Microsoft 365 Government how to buy - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Apologies for the delay in responding. We appreciate your comment and will look further into the matter. For now, the product team wanted to clarify that the "How to buy" page is a general customer how to buy page, and does not have specific service documentation for Partners or LSP/CSP/AOSG or others. It also does not have licensing specifics since that information should be in the partner onboarding documentation. So, please work with your partner support team and OCP for supporting documentation.
