### ISSUE TITLE
Possible contradiction in description of sending limits + additional question about standalone options

### ISSUE THREAD

**Issue by joweiser** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#568]
In the descriptions about sending limits there is contradiction information about what happens when these limits are reached:
![image](https://user-images.githubusercontent.com/808067/123060432-09424980-d40b-11eb-92d9-0e1c32765843.png)
Above the "Sending limits" table it says that "the messages will be rejected and the client will need to retry".
Below in the purple area explaning the footnotes it is mentioned that "any excess in message submission will be throttled and successively carried over to the following minutes. This will typically not block the sender's account".
This reads to me like a contradiction.
Which one is true?

Below this section there is a similar table "Sending limits across standalone options".
The same contradiction probably applies to the "Message rate limit" in this table as well.
How do these limits work with the standalone options?

One more thing:
In the purple footnote area visible in the screenshot above there is a link to another option: "For this use case, options 2 and 3 here are recommended instead."
I understand these options and we are currently working with the customer to consider these options.
However I want to know how the existing limits are working exactly to give proper advice in this situation.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#receiving-and-sending-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @joweiser 

These are not contradicting and actually two completely different things –

1.	The first one is about SMTP Client submission where a user is authenticated using SMTP Protocol and submitting email. If this user connection is throttled because of higher submit limit, the email will be rejected.
2.	The second one is when the client is not using SMTP Client submission method but connected to the mailbox store using other clients for example Outlook or OWA and is sending more that the limit. Those email will be delayed and eventually sent in the following minute.

For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
