### ISSUE TITLE
Azure AD Identity Protection Licensing

### ISSUE THREAD

**Issue by BlueOdyssey** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#603]
Under Azure [Active Directory Identity Protection, which licenses provide the rights for a user to benefit from the service](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service), Azure Active Directory Plan 1 is listed however Azure AD P1 includes very limited to non-existent features for IDP as highlighted [here](https://docs.microsoft.com/en-us/azure/active-directory/identity-protection/overview-identity-protection#license-requirements). This needs to be called out as a limitation here, given that this is the licensing guidance page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I spoke with the product team and they said the S&C Guidance page does not call out any features, but notes which plans include AAD P1/P2: [https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#azure-active-directory-identity-protection](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fservicedescriptions%2Fmicrosoft-365-service-descriptions%2Fmicrosoft-365-tenantlevel-services-licensing-guidance%2Fmicrosoft-365-security-compliance-licensing-guidance%23azure-active-directory-identity-protection&data=04%7C01%7Cv-annhem%40microsoft.com%7C158645c298be4ed2d74b08d9e76e9c78%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637795284525427246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BLkbBUxqUdGKr41Ex6xP2KD5nW0MJRxEjU7wEPEeycU%3D&reserved=0) but links to the page that does: [https://docs.microsoft.com/en-us/azure/active-directory/identity-protection/overview-identity-protection#license-requirements](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Factive-directory%2Fidentity-protection%2Foverview-identity-protection%23license-requirements&data=04%7C01%7Cv-annhem%40microsoft.com%7C158645c298be4ed2d74b08d9e76e9c78%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637795284525427246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OBfa%2BjJubkzTE7TjPt9MIoGwq12lX7rYUNcqEr7wSBs%3D&reserved=0)

I'll reach out to the feature page owner since it may be incorrect. Thanks!

**Comment by annferre** [comment]
Hi there, we will be updating the link to the following document: https://docs.microsoft.com/en-us/azure/active-directory/identity-protection/overview-identity-protection#license-requirements. Since the page is to be just informational and not a licensing page, the plan information will remain the same, so as not to have to update various pages in case the features change. Let me know if you have questions. Thanks!

**Comment by annferre** [comment]
Hi there, thank you again for your comment. The updated link is live. Let me know if you have any further questions. Thanks again!
