### ISSUE TITLE
Incomplete "Sending limits:" information

### ISSUE THREAD

**Issue by NuAlex** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#626]
Hello OfficeDocs team,
Under "Sending limits" it is stated that "Recipient proxy address limit" is 400 addresses, but that is not true for synced users from on-premises AD. If an AD user has more than 300 proxyaddresses, Azure AD Connect might not be able to sync the object to Azure AD due to error ExceededAllowedLength. 

For more information about synced users' limits, please consult the following page: 
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/tshoot-connect-sync-errors#largeobject-or-exceededallowedlength

Thanks so much!

/Nuno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits?source=docs#sending-limits-1)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment! I have forwarded your request to the product team, and I'll get back to you as soon as I receive the response. Thanks again!

**Comment by annferre** [comment]
HI there, I just wanted to let you know we have updated the information on the page to the below. Let me know if you have further questions or concerns. Thanks again for your contribution.
<html>
<body>
<div class="table-scroll-wrapper has-inner-focus table-scroll-wrapper-scrollable" tabindex="0" role="group" aria-label="Horizontally scrollable data" style="box-sizing: inherit; outline: none; overflow: auto hidden; border: 1px solid var(--theme-border); margin: 1px; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Recipient proxy address limit3 | 300 | 300 | 300 | 300 | 300 | 300 | 300
-- | -- | -- | -- | -- | -- | -- | --
Message rate limit4 | 30 messages per minute | 30 messages per minute | 30 messages per minute | 30 messages per minute | 30 messages per minute | 30 messages per minute | 30 messages per minute

</div><div class="alert is-info" style="box-sizing: inherit; outline-color: var(--theme-text); overflow-wrap: break-word; background-color: var(--theme-info-background); border: 1px solid var(--theme-info-background-glow-high-contrast); border-radius: 6px; color: rgb(23, 23, 23); display: block; font-size: 16px; margin-top: 1rem; padding: 1rem; position: relative; transition: height 0.5s ease-in 0s, opacity 0.5s ease-in 0s; word-break: break-word; font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="alert-title" style="box-sizing: inherit; margin: 0px; padding: 0px; outline-color: inherit; max-width: 100%; overflow-wrap: break-word; color: var(--theme-info-dark); font-weight: 600;"><span class="docon docon-status-error-outline" aria-hidden="true" style="box-sizing: inherit; outline-color: inherit; speak: none; -webkit-font-smoothing: antialiased; direction: ltr; display: inline-block; font-family: docons; font-size: inherit; font-style: normal; font-variant: normal; font-weight: 400; line-height: 16px; text-align: center; text-transform: none;"></span><span> </span>Note</p><p style="box-sizing: inherit; margin: 1rem 0px 0px; padding: 0px; outline-color: inherit; max-width: 100%; overflow-wrap: break-word;"><sup style="box-sizing: inherit; font-size: 12px; line-height: 0; position: relative; vertical-align: baseline; top: -0.5em; outline-color: inherit;">1</sup><span> </span>After the recipient rate limit is reached, messages can't be sent from the mailbox until the number of recipients that were sent messages in the past 24 hours drops below the limit. For example, a user sends an email message to 5000 recipients at 09:00 AM, then sends another message to 2500 recipients at 10:00 AM, and then sends another message to 2500 recipients at 11:00 AM, hitting the limit of 10,000 messages. The user won't be able to send messages again until 09:00 AM the next day.<br style="box-sizing: inherit; outline-color: inherit;"><sup style="box-sizing: inherit; font-size: 12px; line-height: 0; position: relative; vertical-align: baseline; top: -0.5em; outline-color: inherit;">2</sup><span> </span>You can customize recipient limits between 1 and 1000 for existing mailboxes and for new mailboxes that will be created in the future. Edit the recipient limit on existing mailboxes individually or in bulk using the Exchange admin center and customize the default setting for new mailboxes via Remote PowerShell. For more information, see<span> </span><a href="https://techcommunity.microsoft.com/t5/exchange-team-blog/customizable-recipient-limits-in-office-365/ba-p/1183228" data-linktype="external" style="box-sizing: inherit; background-color: transparent; outline-color: inherit; overflow-wrap: break-word; color: var(--theme-info-dark); cursor: pointer; text-decoration: none; outline-style: initial; outline-width: 0px; font-weight: 600;">Customizable recipient limits in Office 365</a>.<br style="box-sizing: inherit; outline-color: inherit;"><sup style="box-sizing: inherit; font-size: 12px; line-height: 0; position: relative; vertical-align: baseline; top: -0.5em; outline-color: inherit;">3</sup><span> </span>These numbers can vary slightly since the limit is based on number of characters so the number of email addresses will vary depending on how long they are. As a rule of thumb, it is safer to assume that the limit of smtp addresses in ProxyAddresses is approximately 300 addresses to leave room for future growth of the object and its populated attributes.</p></div>
</body>
</html>
