### ISSUE TITLE
Wisconsin

### ISSUE THREAD

**Issue by deonlewisduke** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#64]
I will resume my test of this system tomorrow after checking if my state has any issues with it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8787e860-9615-fd73-e89a-8a93f8e1c40b
* Version Independent ID: 8771ae61-125e-cd6f-2d21-0954bdd8ea8c
* Content: [GCC](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@deonlewisduke - Thanks for letting us know that you're testing our GCC service. We appreciate it! Since you didn't indicate any actual issues with this article, I'm going to close this. During your GCC testing, if you notice any inaccuracies in the article or missing information, please feel free to open another issue with the specific details for us to address. Thanks!
