### ISSUE TITLE
Why does the Exchange Online page include a section for To Do?

### ISSUE THREAD

**Issue by Foamcow** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#685]
I find it odd that the service description for Exchange includes a section for To Do. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff8bcc8-4789-dc65-c108-ee0641c7c3b7
* Version Independent ID: 20fff9c3-700c-30f1-0714-535957ef40e9
* Content: [Exchange Online for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded the question to the Product Team. I'll keep you posted on response. Thanks again!

**Comment by annferre** [comment]
Hi there, I received feedback regarding this matter, from the product team. They said "the Exchange Online for Gov service description references To Do because Exchange Online is a requirement for using it. To Do users need mailboxes in Exchange Online for tasks in Microsoft To Do to sync and store. Since these are crucial functions of the app, users without cloud-based mailboxes through Exchange Online will not be able to use Microsoft To Do.  And there are some nuances to using To Do in the GCC environment, which is why they are covered in this doc." Please reopen if you have further questions. Thanks again for your comment!
