### ISSUE TITLE
Azure Active Directory Identity Protection - Which licenses provide the rights for a user to benefit from the service

### ISSUE THREAD

**Issue by cybergeeks-cloud** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#716]
[Please, review the section Which licenses provide the rights for a user to benefit from the service? It looks like Identity Protection could be used with Azure AD Premium 1 licenses, which is not the case since we need Azure AD P2.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#azure-active-directory-identity-protection)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team, and I will get back to you as soon as I receive a response. Thanks again!

**Comment by annferre** [comment]
Hi there, the Product team agreed you make a good point since the section is specific to ID Protection not AAD P1/P2. So, updating to the below, and I'll let you know once it's updated.

Change from:

Which licenses provide the rights for a user to benefit from the service?
•	Azure Active Directory Plan 1: Microsoft 365 E3/A3/G3/F1/F3, Enterprise Mobility & Security E3 and Microsoft 365 Business Premium
•	Azure Active Directory Plan 2: Microsoft 365 E5/A5/G5, Enterprise Mobility & Security E5, Microsoft 365 E5/F5 Security and Microsoft 365 F5 Security & Compliance


To:

Which licenses provide the rights for a user to benefit from the service?
•	Microsoft 365 E5/A5/G5, Enterprise Mobility & Security A5/E5/G5, Microsoft 365 A5/E5/F5/G5 Security and Microsoft 365 F5 Security & Compliance

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the edit is live. Please reopen if you have further questions. Thanks again for your comment.
