### ISSUE TITLE
Source repository behind published docs is invisible

### ISSUE THREAD

**Issue by sassdawe** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#735]
Greetings,

I was looking for [https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/) but it seams to be private.

Could you maybe consider making it `public`? 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I spoke with the repository owners, and unfortunately, these are documents that require permissions to be changed. They need to remain private because the information that gets published goes through an approval process with various stages. The public is welcome to open a GitHub issue to point out missing or incorrect content and it will be investigated, however they cannot make any changes to the content themselves. Thank you for your comment. Please reopen if you have further questions or concerns.
