### ISSUE TITLE
Clarify what "Delegate Access" means

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#763]
Can we clarify what "Delegate Access" means? This is not available for Microsoft 365 F3 & Office 365 F3 and Exchange Online Kiosk. If a user has this license, does that mean that:

1) He/She can't delegate access of THEIR mailbox to someone else.
**_or_**
2) He/She can't access another mailbox, user mailbox or shared mailbox, that he/she has been delegated access?

Scenario: We have 100 users that need to access a Shared Mailbox. Will Microsoft 365 F3 work for them?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
I'm sorry that you're having this issue. 

For Support options, please see: https://learn.microsoft.com/en-us/microsoft-365/admin/m365-feature-descriptions?view=o365-worldwide&tabs=Support

**Comment by JonesMikael** [comment]
This is not an technical issue that needs support. It’s me reading the documentation to see if se are license compliant or not and the documentation needs clarification on what that ”Delegate Access” part of ” Delegate access and hierarchical address book” really means.

**Comment by SeanGit88** [comment]
Thanks for the reply.   I will let the product team know and will update the article as necessary based on their response.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
