### ISSUE TITLE
What does CE-1 stand for?

### ISSUE THREAD

**Issue by gabsto-ms** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#777]
[Hello! What does CE-1 stand for in the note:
"10 Viva Sales users must have M365 E3/E5 products and capabilities as well as Dynamics 365 Sales (Enterprise, Premium, MRSs, or **CE-1**)." Maybe we should use the full name, to avoid confusions. Thanks]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d53db8b-8a48-4608-5613-e94e81d61281
* Version Independent ID: 6241e635-edac-9e14-c4b8-47e3db93a124
* Content: [Microsoft Viva service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-viva-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-viva-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-viva-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated (removed). thanks for your feedback.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
