### ISSUE TITLE
Exchange Online K1 license reference

### ISSUE THREAD

**Issue by Snozzberries** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#795]
The note for M365 F1 references an Exchange Online K1 license, but that does not exist. 

M365 F1 includes an EXO Kiosk license. https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference

Changing the note or adding shared mailboxes as a feature row with EXO Kiosk being excluded may provide better clarity to the requirements for these features, assuming that is the appropriate interpretation. Or possibly if EXO K1 is a reference to the lower features enabled as part of an EXO Kiosk licensed through M365 F1, maybe it needs a reference in the SKU list? Either way it seems like showing a shared mailbox in the feature matrix could clear up a lot of confusion.

> Each user who accesses the Exchange Online service must be assigned to a subscription plan, and each user subscription has its own mailbox. Folders and messages in these mailboxes reside at a Microsoft datacenter. User subscriptions are not required for conference rooms and shared mailboxes. These special mailbox types do not have login credentials, instead, licensed users with the appropriate permissions manage and access them via delegation. Microsoft 365 F1 does not include rights to an Exchange mailbox. To enable a full Teams experience, Microsoft 365 F1 licenses may come with the Exchange Online K1 service plan enabled. Although the Exchange Online K1 service plan will provision a mailbox for the user, Microsoft 365 F1 users are not entitled to use the mailbox. We recommend that you disable Outlook on the web via [these steps](https://learn.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-outlook-web-app) and ask your users not to access the Exchange mailbox via any other methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by SeanGit88** [comment]
Hello, K1 reference has been removed.  thank you!
