### ISSUE TITLE
Number of hub sites associated limits?

### ISSUE THREAD

**Issue by rohit404404** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#826]
Is there a limit on number of sites that can be connected to single Hub. We have around 2K site collections.

I do see limit with 500 navigation object, but that does not mean Hub can only have 500 sites associated, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by SeanGit88** [comment]
Hi, these are general guidelines.  For more specifics, please refer to this:  https://learn.microsoft.com/en-us/sharepoint/planning-hub-sites   thank you!
