### ISSUE TITLE
It is 300 per product.

### ISSUE THREAD

**Issue by HenrikMejnhardtNielsen** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#847]
This text is wrong!
- It is 300 **per product**.
"For example, you can have up to 300 seats collectively for Microsoft 365 Business Basic, Microsoft 365 Business Standard, and/or Microsoft 365 Business Premium"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Microsoft 365 and Office 365 plan options - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
